### ISSUE TITLE
does this work with web+app gtag js?

### ISSUE THREAD

**Issue by Freundschaft** [dart-lang/usage#138]
I am trying to use this with the new web + app analytics by google, but i never receive events. is it possible that this is not possible with this library?

**Comment by fertrig** [comment]
I had the same issue. I resolved it by creating a "web" property which generates a UA-* tracking ID. Using that tracking ID I started getting events. To see `screenview` events I had to create a "Mobile app" view.

**Comment by Freundschaft** [comment]
I figured out that google analytics now uses gtag.js for reporting. so it looks like this library doesn't support it.
I switched to using this instead https://github.com/Freundschaft/gtag_analytics

**Comment by hpoul** [comment]
It looks like the measurement protocol for Google Analytics 4 (ie. web+app) was published https://developers.google.com/analytics/devguides/collection/protocol/ga4 🎉️ 

any plans on supporting it? 🤔️

**Comment by hpoul** [comment]
Since Universal Analytics will stop processing events next year, I guess this library would be pretty useless?
The GA4 protocol now requires a firebase "app_instance_id" and the documentation states:

> The intent of the Measurement Protocol is to augment automatic collection via gtag, Tag Manager, and Google Analytics for Firebase **not to replace them**.

So I guess that's not really an option either?

**Comment by vorte** [comment]
I just started integrating with usage and unfortuantely had to use an UA id which as mentioned above will stop working in 9 months.

Any plans to support ga4 in this project? Unfortunately I couldn't find any other flutter library that supports ga4.

**Comment by devoncarew** [comment]
Hi - we're aware of the GA4 changeover; the latest from [here](https://support.google.com/analytics/answer/11583528?hl=en#:~:text=Until%20July%201%2C%202023%2C%20you,for%20at%20least%20six%20months.) is `All standard Universal Analytics properties will stop processing new hits on July 1, 2023`.

I don't yet know whether we'll support GA4 in this package or leave that to another package. If we did support it here, it's enough of a protocol change that we likely wouldn't try for backwards compatibility in the APIs; i.e. v4 of this package and v5 would have different APIs (one that matched the needs of the older measurement protocol and one that matched the needs of GA4).

I'll create an issue to track figuring out if we're moving this package forward and reference that issue here.

**Comment by devoncarew** [comment]
I'm going to close this issue in favor of a general GA4 tracking issue here: https://github.com/dart-lang/usage/issues/185.
